Repository samuelduchesne/archetypal, pull requests merged in 2022-07, with the labels that each got.

#342 Added ability to combine two UmiTemplateLibrary objects to form a larger one
  archetypal/umi_template.py
  tests/test_umi.py
Labels: new feature, enhancement

#349 __getitem__ and __setitem__ has been implemented for the UmiBase class
  archetypal/template/umi_base.py
  tests/test_template.py
Labels: new feature

#351 VentilationType was previously not included in dict
  archetypal/template/conditioning.py
  archetypal/template/load.py
  archetypal/template/ventilation.py
  archetypal/template/window_setting.py
Labels: bug

#358 An issue affecting invalid GasMaterial names has been fixed
  archetypal/template/materials/gas_material.py
  tests/test_template.py
Labels: bug

#360 An issue when the initialization of subclasses of UmiBase fails has been fixed
  archetypal/template/building_template.py
  archetypal/template/conditioning.py
  archetypal/template/constructions/opaque_construction.py
  archetypal/template/constructions/window_construction.py
  archetypal/template/dhw.py
  archetypal/template/load.py
  archetypal/template/materials/gas_material.py
  archetypal/template/materials/glazing_material.py
  archetypal/template/materials/nomass_material.py
  archetypal/template/materials/opaque_material.py
  archetypal/template/schedule.py
  archetypal/template/structure.py
  archetypal/template/umi_base.py
  archetypal/template/ventilation.py
  archetypal/template/window_setting.py
  archetypal/template/zone_construction_set.py
  archetypal/template/zonedefinition.py
  archetypal/umi_template.py
Labels: bug
